### ISSUE TITLE
Can't we set bash as the default shell when logging via `adb shell`?

### ISSUE THREAD

**Issue by esauvisky** [Zackptg5/Bash-For-Android#1]
Hey there. I also have a little magisk module with bash and other binaries that I use frequently. But so far, no matter how much I research, it seems that there is no way to either:

- Use bash as the default shell whenever you're on interactive mode (or any mode, I don't really care, but I've read it _might_ break something).
- Nor even run a script or command after `adb shell` that would spawn `bash`, _which looks ridiculously trivial at first,_ but it's been months I've been looking for something like this and I had no success at all.

The only proper solution looks like it's recompiling adbd _(because the paths are hardcoded on `system/core/adb/services.c`), but I'd much rather prefer a device-wide solution.

Any ideas?

**Comment by roblav96** [comment]
@esauvisky

[Magisk-Modules-Repo/terminalmods](https://github.com/Magisk-Modules-Repo/terminalmods)

> This module edits the files `system/etc/mkshrc` and `system/etc/bash/bashrc`.

Hope this helps =]

**Comment by esauvisky** [comment]
Thanks! I already knew about terminalmods. So much actually, that I forked it and have been trying to develop this feature on top of it. Unfortunately I still couldn't get it to automatically spawn bash instead of the default shell.

I'm gonna open an issue there, it definitely makes more sense now that I thought about it :sweat_smile: 

Thank you! :)

**Comment by Zackptg5** [comment]
Out of curiosity, does the latest version show as as bash when you use adb? I added an option in which bash can replace sh each boot in a way that won't break the boot process

**Comment by esauvisky** [comment]
Cool, thanks for giving it a go!

Unfortunately I just tried it and it doesn't look like it works:
![Peek 2019-03-31 20-23](https://user-images.githubusercontent.com/18354658/55296677-3c93fa80-53f3-11e9-9a14-f51f84d6a6b1.gif)

Am I doing something wrong? _I am quite skilled at PEBCAKing..._ :joy:

**Comment by Zackptg5** [comment]
Try typing `help` and see what shows up

**Comment by esauvisky** [comment]
Oh, it was a PEBCAK! See, toldya! :rofl:

**Comment by esauvisky** [comment]
For some reason it's not sourcing my .bashrc in /sdcard despite [/system/etc/bash/bashrc](https://github.com/Zackptg5/Bash-For-Android/blob/master/system/etc/bash/bashrc).

Also getting an error `No daemon is currently running` when trying to log in as root with su, but only happens via adb, works fine from within the device :thinking:

These are probably unrelated though, and most likely my fault as well... :roll_eyes: I'll close the issue.

And hey, thanks a bunch! It's definitely going to be useful. 
Keep up the good work! :clap:
